version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:  # ✅ Add a health check
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # ✅ Wait for DB to be healthy
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    command: >
      sh -c "python -c 'from app.db.database import engine; from app.models.sqlalchemy.sql_locations import Base; Base.metadata.create_all(bind=engine)' &&
      python seed.py &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000"

  pgadmin:  # ✅ Add pgAdmin service
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pgdata: